### ISSUE TITLE
Duplicate module name: react-native-vector-icons

### ISSUE THREAD

**Issue by sleepforests** [maskzh/rn-weui#11]
启动报错，删除掉目录【/Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/rn-weui/node_modules/react-native】就可以启动了，应该是依赖重复了。

```
 Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/rn-weui/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/rn-weui/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at /Users/bain.wang/Documents/workspace/ReactNative/ReactNativeWeuiExample/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! ReactNativeWeuiExample@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactNativeWeuiExample@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactNativeWeuiExample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ReactNativeWeuiExample
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ReactNativeWeuiExample
npm ERR! There is likely additional logging output above.

```

**Comment by maskzh** [comment]
建议 Node 版本 >= 6 哦
